name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    
      # Получаем исходники
      - name: Checkout
        uses: actions/checkout@v4

      # Подключаем MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Собираем 32-битную Release версию
      - name: Build
        run: msbuild eob3.sln /m /p:Configuration=Release /p:Platform=x86

      # Сохраняем готовый EXE
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: eob3-win32
          path: Release/eob3.exe
