name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2
    - run: msbuild eob3.sln /m /p:Configuration=Release /p:Platform=x86
    - shell: pwsh
      run: Compress-Archive Release\eob3.exe eob3-win32.zip
    - uses: softprops/action-gh-release@v2
      with:
        files: eob3-win32.zip
